### PR TITLE
Support addLockCode

### PR DESCRIPTION
**Pull request by fetchak**
Adds support for new `addLockCode` endpoint.

No spec since `addMessage` doesn't have one either.

### CODE REVIEW

**Comment by fetchak** [comment]
Is someone able to approve/disapprove this PR?

**Comment by cemeyer2** [comment]
LGTM, but I no longer have write access to this repository. @neoword might you be able to merge this in?

**Comment by fetchak** [comment]
@neoword can you take a quick look at this PR?

**Review by neoword — APPROVED** [review]
Approve

**Comment by neoword** [comment]
@cemeyer2 what release should this go into? I'll create a milestone and assign it to that.

**Pull request merged**
